/*
# Create anonymous policy analytics

1. New Tables
- `analytics_events` stores anonymous activity generated by the public policy portal.
- `visitor_id` is a random browser identifier and is not linked to an account or email.
- `session_id` identifies one browsing session.
- `event_type` identifies page views, engagement heartbeats, scroll milestones, downloads, PDF opens, and prints.
- `route`, `category`, `policy_id`, `policy_slug`, `policy_title` identify the viewed area without storing personal data.
- `duration_seconds` stores approximate time observed in the page.
- `scroll_percent` stores the highest observed scroll percentage.
- `created_at` stores when the event was recorded.

2. Security
- Row level security is enabled.
- Anonymous and authenticated visitors may insert analytics events so public pages can measure activity.
- Visitors cannot read, update, or delete analytics events.
- Authenticated panel users with an admin, auditor, or viewer role may read analytics.
- No analytics event contains an email, name, IP address, or authentication identifier.

3. Performance
- Indexes support reporting by event type, policy, category, and creation time.
*/

CREATE TABLE IF NOT EXISTS public.analytics_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  visitor_id text NOT NULL CHECK (char_length(visitor_id) BETWEEN 16 AND 80),
  session_id text NOT NULL CHECK (char_length(session_id) BETWEEN 16 AND 80),
  event_type text NOT NULL CHECK (event_type IN ('page_view', 'engagement', 'scroll', 'download', 'pdf_open', 'print')),
  route text NOT NULL CHECK (char_length(route) BETWEEN 1 AND 240),
  category text,
  policy_id uuid REFERENCES public.policies(id) ON DELETE SET NULL,
  policy_slug text,
  policy_title text,
  duration_seconds integer CHECK (duration_seconds IS NULL OR (duration_seconds >= 0 AND duration_seconds <= 86400)),
  scroll_percent integer CHECK (scroll_percent IS NULL OR (scroll_percent BETWEEN 0 AND 100)),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public visitors can record analytics" ON public.analytics_events;
CREATE POLICY "Public visitors can record analytics"
ON public.analytics_events FOR INSERT
TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can read analytics" ON public.analytics_events;
CREATE POLICY "Admins can read analytics"
ON public.analytics_events FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.admin_users
    WHERE admin_users.id = auth.uid()
      AND admin_users.is_active = true
      AND admin_users.role IN ('superadmin', 'admin', 'auditor', 'viewer')
  )
);

DROP POLICY IF EXISTS "Visitors cannot update analytics" ON public.analytics_events;
CREATE POLICY "Visitors cannot update analytics"
ON public.analytics_events FOR UPDATE
TO anon, authenticated
USING (false)
WITH CHECK (false);

DROP POLICY IF EXISTS "Visitors cannot delete analytics" ON public.analytics_events;
CREATE POLICY "Visitors cannot delete analytics"
ON public.analytics_events FOR DELETE
TO anon, authenticated
USING (false);

REVOKE SELECT, UPDATE, DELETE ON public.analytics_events FROM anon;
REVOKE UPDATE, DELETE ON public.analytics_events FROM authenticated;
GRANT INSERT ON public.analytics_events TO anon, authenticated;
GRANT SELECT ON public.analytics_events TO authenticated;

CREATE INDEX IF NOT EXISTS analytics_events_created_at_idx ON public.analytics_events (created_at DESC);
CREATE INDEX IF NOT EXISTS analytics_events_policy_event_idx ON public.analytics_events (policy_id, event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS analytics_events_category_event_idx ON public.analytics_events (category, event_type, created_at DESC);
